### ISSUE TITLE
BUG : change the background color of body 

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/StarterHive#157]
# TODO:
- Change of background color of body to new gradient .
- Gradient code ` bg-gradient-to-r from-gray-700 via-gray-900 to-black`
-
 
![sfad](https://github.com/ArslanYM/StarterHive/assets/104521101/f54c4712-1bd1-4321-a97d-b84aef720f7c)

**Comment by ArslanYM** [comment]
@masif2002  Would you like to fix this?

**Comment by masif2002** [comment]
@ArslanYM Sure. But would you like to mention how I can reproduce the issue, so that I can check once I've made the changes

I'm not able to reproduce the issue for the screen size of Iphone 12 pro?
![image](https://github.com/ArslanYM/StarterHive/assets/94846379/9c4a8203-f635-4d4f-a28f-47e522ed2ee0)

**Comment by ArslanYM** [comment]
This issue will probably still exists on large screen devices. if not that you can maybe try adding iphone 8plus to your google developer tools.

**Comment by masif2002** [comment]
> This issue will probably still exists on large screen devices. if not that you can maybe try adding iphone 8plus to your google developer tools.

Somehow, the issue does not exist in larger devices. Let me check it once with Iphone 8plus

**Comment by prasenjitpawar22** [comment]
on the docs page, it is much better visible
added PR for this issue #166 

<img width="960" alt="image" src="https://github.com/ArslanYM/StarterHive/assets/29477488/a34f78ec-64e9-476a-bf78-ca009720bdea">
