### ISSUE TITLE
[FEAT]: Provide an introduction of the project in the Readme.md file

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/StarterHive#28]
The introduction should provide: 
- A easy to understand idea about the project 
- A small description of how it will help people
- Links to discord and the community page

**Comment by appleconda** [comment]
I think I can do it. I have understood that this project is aimed at helping beginners understand how the process of contributing to opensource on github works. I will happy to add an introduction of the project in the readme.md and will also add the links. 
So do you think you can assign me the issue?

**Comment by ArslanYM** [comment]
@appleconda Sure, I would love to.

**Comment by ArslanYM** [comment]
@appleconda Any progress?

**Comment by appleconda** [comment]
I did do pull request with the changes. It said that "contributors haven't reviewed this pull request yet" I thought you would have to approve the request. Also upon waiting a few days I deleted the repo that I forked would that have meant that the PR also got removed? 
I am sorry If I sound very newbie because I am.

**Comment by ArslanYM** [comment]
I guess that is what happened. Im sorry for not checking your PR, I was on a break for a week.
